  [#assign doc_table_index=1/]
  [@displaySection "一、培养目标和专业特色" 1/]
  [@multi_line_p]${(doc.getText("summary").contents)!}[/@]
  [@displaySection "（一）人才培养目标" 2/]
  [@multi_line_p]${(doc.getText("goals.1").contents)!}[/@]
  [#list doc.objectives?sort_by("code") as obj]
    [@p2]培养目标${obj.code}：${obj.contents!}[/@]
  [/#list]
  [@displaySection "（二）人才培养特色" 2/]
  [@multi_line_p]${(doc.getText("goals.2").contents)!}[/@]
  [@displaySection "二、学制和最低学分要求" 1/]
  [@p (doc.getText("credits").contents)!/]
  [@displaySection "三、主要课程和结构" 1/]
  [@displaySection "（一）主要课程" 2/]
  [@multi_line_p]${(doc.getText("courses").contents)!}[/@]
  [@displaySection "（二）课程结构" 2/]
  [#include "credit_stat.ftl"/]
  [@displaySection "七、专业教学计划表" 1/]
  [@p]1.专业教学计划表（见附表）[/@]

