[#ftl]
[@b.head /]
[@b.toolbar title="专业替代课程维护"]
    bar.addBack();
[/@]
[@b.form name="baseCodeSearchForm2" title="专业替代课程基本信息" theme="list"  action=b.rest.save(alt) onsubmit="return checkCourse()"]
    [@base.grade name='alt.fromGrade.id'  label='年级从' maxlength="50" required="true" value=alt.fromGrade!/]
    [@base.grade name='alt.toGrade.id'   label='到' maxlength="50" required="true" value=alt.toGrade!/]
    [@b.select name='alt.department.id' label="院系" items=departs value=alt.department! /]
    [@base.code type='std-types' name='alt.stdType.id'  label="学生类别" value=alt.stdType! /]
    [@b.select name='alt.major.id' label="专业" items=majors value=alt.major! /]
    [@b.select name='alt.direction.id' label='方向' items=directions value=alt.direction! /]
    [@base.course label="原课程" name="originCodes" multiple="true" values=alt.olds required='true'/]
    [@base.course label="替代课程" name="substituteCodes" multiple="true" values=alt.news required='true'/]
    [@b.textarea name='alt.remark' maxLength="300" label='备注' cols="40" rows="1" value=alt.remark!/]
    [@b.formfoot]
        [@b.submit value="action.submit" /]
    [/@]
[/@]
[@b.foot /]
