[#ftl]
[@b.head /]
[@b.toolbar title="免修课程维护"]
    bar.addBack();
[/@]
[@b.form  theme="list"  action=b.rest.save(exempt) ]
    [@base.grade name='exempt.fromGrade.id'  label='年级从' maxlength="50" required="true" value=exempt.fromGrade!/]
    [@base.grade name='exempt.toGrade.id'   label='到' maxlength="50" required="true" value=exempt.toGrade! required="false"/]
    [#if project.eduTypes?size>1]
    [@b.select name='exempt.eduType.id'  label="培养类型" value=exempt.eduType! items=project.eduTypes required="true"/]
    [/#if]
    [@base.code type='education-levels' name='exempt.level.id'  label="培养层次" value=exempt.level! required="true"/]
    [@base.code type='course-types' name='exempt.courseType.id'  label="课程类别" value=exempt.courseType! required="true"/]
    [@base.course name='exempt.course.id' label="课程" value=exempt.course! required="false" /]
    [@b.select name='stdType.id'  label="学生类别" values=exempt.stdTypes! items=project.stdTypes required="true" multiple="true"/]
    [@b.textarea name='exempt.remark' maxLength="300" label='备注' cols="40" rows="1" value=exempt.remark!/]
    [@b.formfoot]
      [#if  project.eduTypes?size == 1 ]
        <input name='exempt.eduType.id' value="${project.eduTypes?first.id}" type="hidden"/>
      [/#if]
      [@b.submit value="action.submit" /]
    [/@]
[/@]
[#list 1..10 as i]
  <br/>
[/#list]
[@b.foot /]
