[#ftl]
[@b.head/]
[@b.messages slash="7"/]
[@b.toolbar title="公共课程方案维护"]
  bar.addBack();
[/@]
[#if plan.persisted]
[@b.nav class="nav-tabs nav-tabs-compact"]
  [@b.navitem href="!edit?id="+plan.id]基本信息[/@]
  [@b.navitem href="course!groups?plan.id="+plan.id]课程设置[/@]
[/@]
[/#if]
[@b.form name="planEditForm"   action=b.rest.save(plan) theme="list"]
    [@b.textfield label="名称" required="true" check="maxLength(30)" name="plan.name" value="${(plan.name)?if_exists}" style="width:200px" maxLength="40"/]
    [@b.select label="起始年级" required="true" name="plan.fromGrade.id" value=plan.fromGrade! items=grades  style="width:100px" /]
    [@b.select label="截止年级" required="true" name="plan.toGrade.id" value=plan.toGrade! items=grades style="width:100px" /]
    [#if project.eduTypes?size>1]
    [@b.select name='plan.eduType.id' label="培养类型" items=project.eduTypes value=plan.eduType! required='true' /]
    [/#if]
    [@b.select label="培养层次" required="true" name="plan.level.id"  style="width:200px;" items=levels empty="..." value=plan.level!/]
    [@b.startend label="有效时间范围" name="plan.beginOn,plan.endOn" required="true,false" start=plan.beginOn! end=plan.endOn!/]
    [@b.formfoot]
        [#if project.eduTypes?size==1]
        <select name='plan.eduType.id' style="display:none"><option value="${project.eduTypes?first.id}" selected>${project.eduTypes?first.name}</option></select>
        [/#if]
        [@b.reset/]
        [@b.submit value="action.submit"/]&nbsp;
    [/@]
[/@]
[@b.foot/]
